server:
  port: 8080

spring:
  application:
    name: gateway-service

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    gateway:
      routes:
        - id: vendor-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/vendors/**
          filters:
            - StripPrefix=1
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1
        - id: customer-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/customers/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1
        - id: paypromo-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/admin/**
          filters:
            - StripPrefix=1
        - id: admin-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/admin/**
          filters:
            - StripPrefix=1
      httpclient:
        connect-timeout: 5000
        response-timeout: 5000

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:4321/realms/ecommerce-realm

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    ip-address: ${spring.cloud.client.ip-address}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG
    com.tlcn.api_gateway: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/gateway.log
    max-size: 10MB

cors:
  allowed-origins: http://localhost:3000
