server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: vendor-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/vendors/**
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/products/**
        - id: customer-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/customers/**
        - id: order-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/orders/**
      httpclient:
        connect-timeout: 5000
        response-timeout: 5000
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:4321/realms/ecommerce-realm

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud: DEBUG
    com.netflix.discovery: DEBUG
    com.tlcn: DEBUG
    org.keycloak: DEBUG

cors:
  allowed-origins: http://localhost:3000
